on:
  workflow_dispatch: {}
name: CI

jobs:
  build_linux:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: update apt 
        run: sudo apt-get update 
      - name: Install deps
        run: sudo apt-get -y install libinput-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build
      - run: cargo build --example readme
      - run: cargo build --example test
      - run: cargo build --example using_config
  build_windows:
    name: Rust project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build
      - run: cargo build --example readme
      - run: cargo build --example test
      - run: cargo build --example using_config
